version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
        image: postgres:15-alpine
        ports:
          - 5432
        volumes:
          - ~/apps/postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_PASSWORD=S3cret
          - POSTGRES_USER=citizix_user
          - POSTGRES_DB=citizix_db
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
